stages:
  - deploy

deploy-prod:
  stage: deploy
  variables:
    BRANCH_REF: master
  script:
    - git fetch
    - git checkout $BRANCH_REF
    - git pull origin $BRANCH_REF
    - npm install
    - rm -rf /opt/rpsls/www
    - ln -s $CI_PROJECT_DIR /opt/rpsls/www
  tags:
    - sheldon
    - production
